# custom hyprsunset.conf file by egnrse
# (https://github.com/egnrse/configs)
# for more configuration options, refer to https://wiki.hypr.land/Hypr-Ecosystem/hyprsunset/

max-gamma = 200

profile {
	temperature = 6000
	gamma = 1.0
}
