# custom hyprpaper.conf file by egnrse
# (https://github.com/egnrse/configs)
# for more configuration options, refer to https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
#
# To run hyprpaper at startup edit hyprland.lua or run 'systemctl --user enable --now hyprpaper.service'

#wallpaper {
#    monitor = 
#    path = ~/myFile.jxl
#    fit_mode = cover
#}
